
LEFT = 1.0
RIGHT = 1.0
GRAPH = {
    'PO': {'HOUSE_1': RIGHT + 4 + RIGHT + 1 + LEFT, 
            'HOUSE_2': RIGHT + 2 + RIGHT + 11 + LEFT, 
            'HOUSE_3': RIGHT + 2 + RIGHT + 6 + LEFT + 1 + RIGHT, 
            'HOUSE_4': RIGHT + 2 + RIGHT + 3 + RIGHT, 
            'HOUSE_5': LEFT + 1 + LEFT + 9 + LEFT, 
            'HOUSE_6': LEFT + 1 + LEFT + 11 + RIGHT + 2 + LEFT, 
            'HOUSE_7': LEFT + 9, 
            'HOUSE_8':  LEFT + 6 + LEFT + 3 + LEFT, 
            'HOUSE_9': LEFT + 9 + LEFT + 9 + RIGHT, 
            'HOUSE_10': LEFT + 1 + LEFT + 6 + RIGHT + 2 + LEFT + 2 + RIGHT + 2 + LEFT, 
            'CHARGER_0': LEFT + 2 + RIGHT, 
            'CHARGER_1': RIGHT + 2 + RIGHT + 8 + LEFT, 
            'CHARGER_2': LEFT + 9 + LEFT + 6 + RIGHT
    },

    'CHARGER_0': {
        'PO': LEFT + 2 + RIGHT,
        'HOUSE_1': RIGHT + 6 + RIGHT + 1 + LEFT,
        'HOUSE_2': RIGHT + 4 + RIGHT + 11 + LEFT,
        'HOUSE_3': RIGHT + 4 + RIGHT + 6 + LEFT + 1 + RIGHT,
        'HOUSE_4': RIGHT + 4 + RIGHT + 3 + RIGHT,
        'HOUSE_5': RIGHT + 1 + RIGHT + 9 + LEFT,
        'HOUSE_6': RIGHT + 1 + RIGHT + 11 + RIGHT + 2 + LEFT,
        'HOUSE_7': LEFT + 7,
        'HOUSE_8': LEFT + 4 + LEFT + 3 + LEFT,
        'HOUSE_9': LEFT + 7 + LEFT + 9 + RIGHT,
        'HOUSE_10': RIGHT + 4 + LEFT + 8 + LEFT + 1 + RIGHT,
        'CHARGER_1': RIGHT + 4 + RIGHT + 8 + LEFT,
        'CHARGER_2': LEFT + 7 + LEFT + 6 + RIGHT
    },
    
    'CHARGER_1': {
        'PO': LEFT + 8 + LEFT + 2 + LEFT,
        'HOUSE_1': LEFT + 2 + RIGHT + 2 + LEFT + 5 + RIGHT,
        'HOUSE_2': RIGHT + 3 + LEFT,
        'HOUSE_3': LEFT + 2 + RIGHT + 1 + RIGHT,
        'HOUSE_4': LEFT + 5 + LEFT,
        'HOUSE_5': LEFT + 1 + LEFT + 3 + LEFT + 2 + LEFT,
        'HOUSE_6': RIGHT + 3 + RIGHT + 5 + LEFT,
        'HOUSE_7': LEFT + 8 + LEFT + 11,
        'HOUSE_8': LEFT + 8 + LEFT + 8 + LEFT + 3 + LEFT,
        'HOUSE_9': RIGHT + 3 + RIGHT + 11 + RIGHT + 2 + LEFT,
        'HOUSE_10': LEFT + 1 + LEFT + 3 + RIGHT + 1 + LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT,            
        'CHARGER_0': LEFT + 8 + LEFT + 4 + RIGHT,
        'CHARGER_2': RIGHT + 3 + RIGHT + 11 + RIGHT + 5 + RIGHT,
    },

    'CHARGER_2': {
        'PO': RIGHT + 6 + RIGHT + 9 + LEFT,
        'HOUSE_1': RIGHT + 6 + RIGHT + 13 + RIGHT + 1 + LEFT,
        'HOUSE_2': LEFT + 5 + LEFT + 11,
        'HOUSE_3': LEFT + 5 + RIGHT + 11 + LEFT + 5 + RIGHT + 1 + RIGHT,
        'HOUSE_4': RIGHT + 6 + RIGHT + 11 + RIGHT + 3 + RIGHT,
        'HOUSE_5': LEFT + 5 + LEFT + 8 + LEFT + 2 + RIGHT,
        'HOUSE_6': LEFT + 5 + LEFT + 6 + RIGHT,
        'HOUSE_7': RIGHT + 6 + LEFT,
        'HOUSE_8': RIGHT + 6 + RIGHT + 3 + RIGHT + 3 + LEFT,
        'HOUSE_9': LEFT + 3 + RIGHT,
        'HOUSE_10': RIGHT + 6 + LEFT + 3 + RIGHT + 8 + LEFT + 1 + RIGHT,
        'CHARGER_0': RIGHT + 6 + RIGHT + 7 + LEFT,
        'CHARGER_1': LEFT + 5 + LEFT + 11 + LEFT + 3 + RIGHT
    },


    'HOUSE_1': {
        'HOUSE_2':  RIGHT + 5 + RIGHT + 2 + LEFT + 5 + LEFT ,
        'HOUSE_3':  RIGHT + 5 + RIGHT + 1 + LEFT,
        'HOUSE_4':  LEFT + 1 + LEFT + 2 + LEFT + 3 + RIGHT,
        'HOUSE_5': RIGHT + 5 + RIGHT + 2 + LEFT + 1 + RIGHT+ 3 + LEFT + 2 + LEFT,
        'HOUSE_6':  RIGHT + 5 + RIGHT + 2 + RIGHT + 5 + RIGHT + 5 + LEFT,
        'HOUSE_7':  LEFT + 1 + LEFT + 13,
        'HOUSE_8':  LEFT + 1 + LEFT + 10 + LEFT + 3 + LEFT,
        'HOUSE_9':  LEFT + 1 + LEFT + 13 + LEFT + 9 + RIGHT,
        'HOUSE_10': LEFT + 1 + LEFT + 10 + LEFT + 8 + LEFT + 1 + RIGHT,
        'PO':       LEFT + 1 + LEFT + 4 + RIGHT,
        'CHARGER_0': LEFT + 1 + LEFT + 6 + RIGHT,
        'CHARGER_1': RIGHT + 5 + RIGHT + 2 + LEFT + 2 + LEFT,
        'CHARGER_2': LEFT + 1 + LEFT + 13 + LEFT + 6 + RIGHT
    },

    'HOUSE_2': {
        'HOUSE_1':  LEFT + 5 + RIGHT + 2 + LEFT + 5 + RIGHT,
        'HOUSE_3':  LEFT + 5 + RIGHT + 1 + RIGHT,
        'HOUSE_4':  LEFT + 8 + LEFT,
        'HOUSE_5':  (2*LEFT) + 3 + RIGHT + 2 + RIGHT,
        'HOUSE_6':  (2*LEFT) + 5 + LEFT,
        'HOUSE_7':  LEFT + 11 + LEFT + 11,
        'HOUSE_8':  (2*LEFT) + 3 + RIGHT + 5 + LEFT + 5 + RIGHT + 3 + RIGHT,
        'HOUSE_9':  (2*LEFT) + 11 + RIGHT + 2 + LEFT,
        'HOUSE_10': (2*LEFT) + 3 + RIGHT + 5 + LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT,
        'PO':       LEFT + 11 + LEFT + 2 + RIGHT,
        'CHARGER_0': LEFT + 11 + LEFT + 4 + RIGHT,
        'CHARGER_1': LEFT + 3 + RIGHT,
        'CHARGER_2': (2*LEFT) + 11 + RIGHT + 5 + LEFT
    },

    'HOUSE_3': {
        'HOUSE_1':   LEFT + 1 + LEFT + 5 + RIGHT,
        'HOUSE_2':   RIGHT + 1 + LEFT + 5 + LEFT,
        'HOUSE_4':   RIGHT + 1 + RIGHT + 3 + RIGHT,
        'HOUSE_5':  RIGHT + 1 + LEFT + 1 + RIGHT + 3 + LEFT + 2 + LEFT,
        'HOUSE_6':  RIGHT + 1 + LEFT + 5 +  RIGHT + 5 + LEFT,
        'HOUSE_7':  RIGHT + 1 + RIGHT + 6 + LEFT + 11,
        'HOUSE_8':  RIGHT + 1 + RIGHT + 6 + LEFT + 8 + LEFT + 3 + LEFT,
        'HOUSE_9':  RIGHT + 1 + LEFT + 5 + RIGHT + 11 + RIGHT + 2 + LEFT,
        'HOUSE_10': RIGHT + 1 + LEFT + 1 + RIGHT + 3 + RIGHT + 1 + LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT,
        'PO':        RIGHT +  1 + RIGHT + 6 + LEFT + 2 + RIGHT,
        'CHARGER_0': RIGHT + 1 + RIGHT + 6 + LEFT + 4 + RIGHT,
        'CHARGER_1': RIGHT + 1 + LEFT + 2 + LEFT,
        'CHARGER_2': RIGHT + 1 + LEFT + 5 + RIGHT + 11 + LEFT + 5 + LEFT
    },

    'HOUSE_4': {
        'HOUSE_1':  RIGHT + 3 + RIGHT + 2 + RIGHT + 1 + LEFT,
        'HOUSE_2':  LEFT + 8 + LEFT,
        'HOUSE_3':  LEFT + 3 + LEFT + 1 + LEFT,
        'HOUSE_5':  LEFT + 4 + RIGHT + 3 + LEFT + 2,
        'HOUSE_6':  LEFT + 8 + RIGHT + 5 + LEFT,
        'HOUSE_7':  RIGHT + 3 + LEFT + 11,
        'HOUSE_8':  RIGHT + 3 + LEFT + 8 + LEFT + 3 + LEFT,
        'HOUSE_9':  RIGHT + 3 + LEFT + 11 + LEFT + 9 + RIGHT,
        'HOUSE_10': LEFT + 4 + RIGHT + 3 + RIGHT + 1 + LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT,
        'PO':        LEFT + 3 + LEFT + 2 + LEFT,
        'CHARGER_0': LEFT + 3 + LEFT + 4 + LEFT,
        'CHARGER_1': LEFT + 5 + LEFT,
        'CHARGER_2': RIGHT + 3 + LEFT + 11 + LEFT + 6 + RIGHT
    },

    'HOUSE_5': {
        'HOUSE_1':  LEFT + 2 + RIGHT + 3 + LEFT+ 1 + RIGHT + 2 + LEFT + 5 + RIGHT,
        'HOUSE_2':  RIGHT + 2 + LEFT + 3,
        'HOUSE_3':  LEFT + 2 + RIGHT + 3 + LEFT + 1 + RIGHT + 1 + RIGHT,
        'HOUSE_4':  LEFT + 2 + RIGHT + 3 + LEFT + 4 + LEFT,
        'HOUSE_6':  RIGHT + 2 + RIGHT + 2 + LEFT,
        'HOUSE_7':  LEFT + 9 + LEFT + 8,
        'HOUSE_8':  LEFT + 3 + LEFT + 5 + RIGHT + 3 + RIGHT,
        'HOUSE_9':  RIGHT + 2 + RIGHT + 8 + RIGHT + 2 + LEFT,
        'HOUSE_10': LEFT + 3 + LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT,
        'PO':        LEFT + 9 + RIGHT + 1 + LEFT,
        'CHARGER_0': LEFT + 9 + LEFT + 1 + RIGHT,
        'CHARGER_1': LEFT + 2 + RIGHT + 3 + RIGHT + 1 + LEFT,      
        'CHARGER_2': RIGHT + 2 + RIGHT + 8 + RIGHT + 5 + LEFT
    },

    'HOUSE_6': {
        'HOUSE_1':  LEFT + 5 + LEFT + 5 + RIGHT + 2 + LEFT + 5 + RIGHT,
        'HOUSE_2':  LEFT + 5,
        'HOUSE_3':  LEFT + 5 + LEFT + 5 +  RIGHT + 1 + RIGHT,
        'HOUSE_4':  LEFT + 5 + LEFT + 8 + LEFT,
        'HOUSE_5':  LEFT + 2 + LEFT + 2 + RIGHT,
        'HOUSE_7':  RIGHT + 6 + RIGHT + 11 + LEFT,
        'HOUSE_8':  LEFT + 2 + LEFT + 5 + LEFT + 5 + RIGHT + 3 + RIGHT,
        'HOUSE_9':  RIGHT + 6 + RIGHT + 2 + LEFT,
        'HOUSE_10': LEFT + 2 + LEFT + 5 + LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT,
        'PO':       LEFT + 2 + LEFT + 11 + RIGHT + 1 + LEFT,
        'CHARGER_0': LEFT + 2 + LEFT + 11 + LEFT + 1 + RIGHT,
        'CHARGER_1': LEFT + 5 + LEFT + 3 + RIGHT,
        'CHARGER_2':  RIGHT + 6 + RIGHT + 5 + LEFT,
    },

    'HOUSE_7': {
        'HOUSE_1':  (2*LEFT) + 13 + RIGHT + 1 + LEFT,
        'HOUSE_2':  (2*LEFT) + 11 + RIGHT + 11 + LEFT,
        'HOUSE_3':  (2*LEFT) + 11 + RIGHT + 6 + LEFT + 1 + RIGHT,
        'HOUSE_4':  (2*LEFT) + 11 + RIGHT + 3 + RIGHT,
        'HOUSE_5':  (2*LEFT) + 8 + RIGHT + 9 + RIGHT,
        'HOUSE_6':   LEFT + 11 + LEFT + 6 + RIGHT,
        'HOUSE_8':  (2*LEFT) + 3 + RIGHT + 3 + LEFT,
        'HOUSE_9':  LEFT + 9 + RIGHT,
        'HOUSE_10': RIGHT + 3 + RIGHT + 9 + LEFT + 1 + RIGHT,
        'PO':       (LEFT*2) + 9 + LEFT,
        'CHARGER_0': (LEFT*2) + 7 + LEFT,
        'CHARGER_1': (2*LEFT) + 11 + RIGHT + 8 + LEFT,
        'CHARGER_2': LEFT + 6 + RIGHT
    },

    'HOUSE_8': {
        'HOUSE_1':  LEFT + 3 + RIGHT + 10 + RIGHT + 1 + LEFT,
        'HOUSE_2':  RIGHT + 3 + LEFT + 5 + RIGHT + 5 + LEFT + 3,
        'HOUSE_3':  LEFT + 3 + RIGHT + 8 + RIGHT + 6 + RIGHT + 1 + RIGHT,
        'HOUSE_4':  LEFT + 3 + RIGHT + 8 + RIGHT + 3 + RIGHT,
        'HOUSE_5':  RIGHT + 3 + LEFT + 5 + RIGHT + 3 + LEFT,
        'HOUSE_6':  RIGHT + 3 + LEFT + 5 + RIGHT + 5 + RIGHT + 2 + LEFT,
        'HOUSE_7':  LEFT + 3 + LEFT + 3,
        'HOUSE_9':  LEFT + 3 + LEFT + 3 + LEFT + 9 + RIGHT,
        'HOUSE_10': RIGHT + 5 + LEFT + 1 + RIGHT,
        'PO':       LEFT + 3 + RIGHT + 6 + LEFT,
        'CHARGER_0': RIGHT + 3 + RIGHT + 4 + LEFT,
        'CHARGER_1': LEFT + 3 + LEFT + 8 + RIGHT + 8 + LEFT,
        'CHARGER_2': LEFT + 3 + LEFT + 3 + LEFT + 6 + RIGHT
    },

    'HOUSE_9': {
        'HOUSE_1':  RIGHT + 9 + RIGHT + 13 + RIGHT + 1 + LEFT,
        'HOUSE_2':  LEFT + 2 + LEFT + 11,
        'HOUSE_3':  LEFT + 2 + LEFT + 11 + LEFT + 5 + RIGHT + 1 + RIGHT,
        'HOUSE_4':  RIGHT + 9 + RIGHT + 11 + RIGHT + 3 + RIGHT,
        'HOUSE_5':  LEFT + 2 + LEFT + 8 + LEFT + 2 + RIGHT,
        'HOUSE_6':  LEFT + 2 + LEFT + 6 + RIGHT,
        'HOUSE_7':  RIGHT + 9 + LEFT,
        'HOUSE_8':  RIGHT + 9 + RIGHT + 3 + RIGHT + 3 + LEFT,
        'HOUSE_10': RIGHT + 9 + RIGHT + 3 + RIGHT + 8 + LEFT + 1 + RIGHT,
        'PO':       RIGHT + 9 + RIGHT + 9 + LEFT,
        'CHARGER_0': RIGHT + 9 + RIGHT + 7 + LEFT,
        'CHARGER_1': LEFT + 2 + LEFT + 11 + LEFT + 3 + RIGHT,
        'CHARGER_2': RIGHT + 3 + LEFT,
    },

    'HOUSE_10': {
        'HOUSE_1':  RIGHT + 1 + RIGHT + 8 + RIGHT + 10 + RIGHT + 1 + LEFT,
        'HOUSE_2':  LEFT + 2 + LEFT + 2 + RIGHT+ 2 + RIGHT + 5 + LEFT + 3,
        'HOUSE_3':  LEFT + 2 + LEFT + 2 + RIGHT + 2 + RIGHT + 1 + LEFT + 3 + LEFT + 1 + RIGHT + 1 + RIGHT,
        'HOUSE_4':  LEFT + 2 + LEFT + 2 + RIGHT + 2 + RIGHT + 1 + LEFT + 3 + RIGHT + 4 + LEFT,
        'HOUSE_5':  LEFT + 2 + LEFT + 2 + RIGHT + 2 + RIGHT + 3 + LEFT,
        'HOUSE_6': LEFT + 2 + LEFT + 2 + RIGHT + 2 + RIGHT + 5 + RIGHT + 2 + LEFT,
        'HOUSE_7':  RIGHT + 1 + RIGHT + 8 + LEFT + 3,
        'HOUSE_8':  RIGHT + 1 + RIGHT + 5 + RIGHT,
        'HOUSE_9':  RIGHT + 1 + RIGHT + 8 + LEFT + 3 + LEFT + 9 + RIGHT,
        'PO':       LEFT + 2 + LEFT + 2 + RIGHT + 2 + LEFT + 6 + RIGHT + 1 + LEFT,
        'CHARGER_0': RIGHT + 1 + RIGHT + 8 + RIGHT + 4 + LEFT,
        'CHARGER_1': LEFT + 2 + LEFT + 2 + RIGHT + 2 + RIGHT + 1  + LEFT + 3 + RIGHT + 1 + LEFT,
        'CHARGER_2': RIGHT + 1 + RIGHT + 8 + LEFT + 3 + LEFT + 6 + RIGHT
    }
}
