<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <link name="camera_colour_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" x="${camera_length}" y="${camera_width}" z="${camera_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_camera_colour_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_colour_link" />
        <!-- Positioned on top of the camera, facing forward (rpy="0 0 0") -->
        <origin xyz="${(base_length + camera_length) / 2.0} 0 ${base_height / 2.0 - 0.02}" rpy="0 0 0" />
    </joint>

    <link name="camera_colour_link_optical" />

    <joint name="camera_colour_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_colour_link"/>
        <child link="camera_colour_link_optical"/>
    </joint>

    <gazebo reference="camera_colour_link">
        <sensor name="camera_colour" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_colour_link_optical</optical_frame_id>
                <camera_info_topic>camera_colour/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>3</update_rate>
            <visualize>true</visualize>
            <topic>camera_colour/image_raw</topic> 

            <plugin
                filename="gz-sim-camera-system"
                name="camera_colour_plugin"/>           
        </sensor>
    </gazebo>

</robot>
