<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Updated properties to match your robot model -->
    <xacro:property name="base_length" value="0.8"/>
    <xacro:property name="base_width"  value="0.6"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_length" value="0.1"/>

    <!-- ========================= -->
    <!-- Base Footprint (empty)   -->
    <!-- ========================= -->
    <link name="base_footprint"/>

    <!-- Fixed transform to base_link (body_link in your model) -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.15"/>
    </joint>

    <!-- =============== -->
    <!-- Base link body  -->
    <!-- =============== -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0"/>
            <material name="body_blue">
                <color rgba="0.09 0.46 0.71 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                   o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <!-- Front box -->
    <joint name="front_box_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_box_link"/>
        <origin xyz="0.18 0 0.20" rpy="0 0 0"/>
    </joint>
    <link name="front_box_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.3 0.25"/>
            </geometry>
            <material name="accent_orange">
                <color rgba="0.95 0.47 0.14 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.4 0.4 0.3"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="1.0" x="0.4" y="0.4" z="0.3" 
                   o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <!-- Basket walls -->
    <joint name="basket_back_joint" type="fixed">
        <parent link="base_link"/>
        <child link="basket_back_link"/>
        <origin xyz="-0.35 0 0.2" rpy="0 0 0"/>
    </joint>
    <link name="basket_back_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.42 0.2"/>
            </geometry>
            <material name="wood_brown">
                <color rgba="0.76 0.60 0.42 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="basket_left_joint" type="fixed">
        <parent link="base_link"/>
        <child link="basket_left_link"/>
        <origin xyz="-0.2 0.2 0.2" rpy="0 0 0"/>
    </joint>
    <link name="basket_left_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.02 0.2"/>
            </geometry>
            <material name="wood_brown">
                <color rgba="0.76 0.60 0.42 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="basket_right_joint" type="fixed">
        <parent link="base_link"/>
        <child link="basket_right_link"/>
        <origin xyz="-0.2 -0.2 0.2" rpy="0 0 0"/>
    </joint>
    <link name="basket_right_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.02 0.2"/>
            </geometry>
            <material name="wood_brown">
                <color rgba="0.76 0.60 0.42 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="basket_front_joint" type="fixed">
        <parent link="base_link"/>
        <child link="basket_front_link"/>
        <origin xyz="-0.05 0 0.2" rpy="0 0 0"/>
    </joint>
    <link name="basket_front_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.42 0.2"/>
            </geometry>
            <material name="light_brown">
                <color rgba="0.89 0.722 0.51 1"/>
            </material>
        </visual>
    </link>

    <!-- Headlights -->
    <joint name="light1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="light1_link"/>
        <origin xyz="${(base_length + 0.01) / 2.0} -0.15 0" rpy="0 -1.5708 0"/>
    </joint>
    <link name="light1_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.01" radius="0.05"/>
            </geometry>
            <material name="headlight_warm">
                <color rgba="1.00 0.96 0.84 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="light2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="light2_link"/>
        <origin xyz="${(base_length + 0.01) / 2.0} 0.15 0" rpy="0 -1.5708 0"/>
    </joint>
    <link name="light2_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.01" radius="0.05"/>
            </geometry>
            <material name="headlight_warm">
                <color rgba="1.00 0.96 0.84 1.0"/>
            </material>
        </visual>
    </link>

    <!-- ============================ -->
    <!-- Rear Wheels (Driven)        -->
    <!-- ============================ -->
    <xacro:macro name="rear_wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="rubber_black">
                    <color rgba="0.06 0.06 0.06 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
                                    o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:rear_wheel_link prefix="rear_left"/>
    <xacro:rear_wheel_link prefix="rear_right"/>

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="${(-(base_length + 0.01) / 2.0) + 0.2} 0.32 -0.1" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="${(-(base_length + 0.01) / 2.0) + 0.2} -0.32 -0.1" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <!-- ============================ -->
    <!-- Front Wheels (Fixed)        -->
    <!-- ============================ -->
    
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${((base_length + 0.01) / 2.0) - 0.2} -0.32 -0.1" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_right_wheel_link">
        <visual>
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="rubber_black">
                <color rgba="0.06 0.06 0.06 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
                                o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
    </link>

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${((base_length + 0.01) / 2.0) - 0.2} 0.32 -0.1" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_left_wheel_link">
        <visual>
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="rubber_black">
                <color rgba="0.06 0.06 0.06 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
                                o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
    </link>

</robot>